version: "3"

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
    ports:
      - 6333:6333
      - 6334:6334
    # expose:
    #   - 6333
    #   - 6334
    #   - 6335
    volumes:
      - ./data/qdrant_data:/qdrant_data
  server:
    image: vectordb-server
    restart: always
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    entrypoint:
      - "/venv/bin/uvicorn"
      - "src.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--reload"
